[package]
org = "wso2"
name = "paypal_send_cancel_invoice"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "paypal.invoices"
version = "1.0.0"
repository = "local"
